// SPDX-License-Identifier: MIT
//
// Styx -- server-side modding framework for 7 Days to Die V2.6
// Copyright (c) 2026 Doowkcol (Jack Lockwood)
//
// This file is part of the Styx open-source plugin set.
// Distributed under the MIT License -- see LICENSE at the repo root.
//

// StyxGameRefs — dumps the game's runtime data registries (items, blocks,
// entity classes, buffs) to searchable markdown reference files.
//
// Why: plugin authors keep guessing at item/block/entity names because
// vanilla XML is huge and rename across patch versions. This plugin runs
// at server startup (after all data has loaded), walks the engine's own
// registries, and writes human-readable tables into:
//
//   server/Mods/Styx/data/game_refs/
//     items.md       — every ItemClass with id, max stack, quality flag, tags
//     blocks.md      — every Block with id, class, material, light opacity
//     entities.md    — every EntityClass with id, tags
//     buffs.md       — every BuffClass with id, name key, hidden flag
//
// Re-run on demand with /gamerefs. Files are overwritten each time so
// they always match the currently-loaded game data (vanilla + any
// modlets that add items/blocks/etc).
//
// Devs can grep these files instead of trying to remember the exact
// vanilla name. Plugin configs that reference items/blocks should
// validate against these as a sanity check.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Styx;
using Styx.Plugins;

[Info("StyxGameRefs", "Doowkcol", "0.1.0")]
public class StyxGameRefs : StyxPlugin
{
    public override string Description => "Writes searchable reference files for items / blocks / entities / buffs to data/game_refs/";

    private string _outDir;

    public override void OnLoad()
    {
        _outDir = Path.Combine(StyxCore.DataPath(), "game_refs");
        Directory.CreateDirectory(_outDir);

        StyxCore.Commands.Register("gamerefs", "Re-dump game data references to data/game_refs/", (ctx, args) =>
        {
            var (n, total) = DumpAll();
            ctx.Reply(string.Format("[00ff66]Wrote {0} files ({1} total entries) to {2}[-]",
                n, total, _outDir));
        });

        Log.Out("[StyxGameRefs] Loaded — output dir: {0}", _outDir);
    }

    /// <summary>Auto-fire on server initialization — all game data registries
    /// are guaranteed populated by then (item/block/entity/buff XML loaded).</summary>
    void OnServerInitialized()
    {
        try
        {
            var (n, total) = DumpAll();
            Log.Out("[StyxGameRefs] Wrote {0} reference files ({1} total entries) to {2}",
                n, total, _outDir);
        }
        catch (Exception e)
        {
            Log.Warning("[StyxGameRefs] Initial dump failed: " + e.Message);
        }
    }

    private (int filesWritten, int totalEntries) DumpAll()
    {
        int files = 0, total = 0;
        try { var c = DumpItems();    if (c >= 0) { files++; total += c; } } catch (Exception e) { Log.Warning("[StyxGameRefs] items dump failed: " + e.Message); }
        try { var c = DumpBlocks();   if (c >= 0) { files++; total += c; } } catch (Exception e) { Log.Warning("[StyxGameRefs] blocks dump failed: " + e.Message); }
        try { var c = DumpEntities(); if (c >= 0) { files++; total += c; } } catch (Exception e) { Log.Warning("[StyxGameRefs] entities dump failed: " + e.Message); }
        try { var c = DumpBuffs();    if (c >= 0) { files++; total += c; } } catch (Exception e) { Log.Warning("[StyxGameRefs] buffs dump failed: " + e.Message); }
        return (files, total);
    }

    // ---- Items ----

    private int DumpItems()
    {
        // ItemClass.list is the engine's canonical ItemClass[] indexed by id.
        // Holes are present (null entries) for unused ids — skip them.
        var arr = ItemClass.list;
        if (arr == null) return -1;

        var rows = new List<ItemClass>();
        for (int i = 0; i < arr.Length; i++)
            if (arr[i] != null && !string.IsNullOrEmpty(arr[i].Name)) rows.Add(arr[i]);
        rows.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));

        var sb = new StringBuilder();
        sb.AppendLine("# Items");
        sb.AppendLine();
        sb.AppendLine("Auto-generated by StyxGameRefs at server startup. " + rows.Count + " items registered.");
        sb.AppendLine();
        sb.AppendLine("| Id | Name | Max Stack | Has Quality |");
        sb.AppendLine("|---:|---|---:|:---:|");
        foreach (var ic in rows)
        {
            // Stacknumber.Value is engine's DataItem (string-backed) — parse defensively.
            int maxStack = 1;
            try
            {
                var raw = ic.Stacknumber?.Value;
                if (raw != null) int.TryParse(raw.ToString(), out maxStack);
            }
            catch { }
            sb.AppendLine(string.Format("| {0} | `{1}` | {2} | {3} |",
                ic.Id, ic.Name, maxStack, ic.HasQuality ? "Y" : ""));
        }
        File.WriteAllText(Path.Combine(_outDir, "items.md"), sb.ToString());
        return rows.Count;
    }

    // ---- Blocks ----

    private int DumpBlocks()
    {
        var arr = Block.list;
        if (arr == null) return -1;

        var rows = new List<Block>();
        for (int i = 0; i < arr.Length; i++)
            if (arr[i] != null && !string.IsNullOrEmpty(arr[i].GetBlockName())) rows.Add(arr[i]);
        rows.Sort((a, b) => string.Compare(a.GetBlockName(), b.GetBlockName(), StringComparison.OrdinalIgnoreCase));

        var sb = new StringBuilder();
        sb.AppendLine("# Blocks");
        sb.AppendLine();
        sb.AppendLine("Auto-generated by StyxGameRefs. " + rows.Count + " blocks registered.");
        sb.AppendLine();
        sb.AppendLine("| Id | Name | Class | Material | Loot |");
        sb.AppendLine("|---:|---|---|---|:---:|");
        foreach (var b in rows)
        {
            string klass = "";
            try { klass = b.GetType().Name; } catch { }
            string material = "";
            try { material = b.blockMaterial?.id ?? ""; } catch { }
            // Detect lootable blocks — those have a non-empty lootList prop or
            // a TileEntity loot subclass.
            bool isLoot = false;
            try
            {
                isLoot = klass.IndexOf("Loot", StringComparison.OrdinalIgnoreCase) >= 0
                      || (b.Properties?.Values?.ContainsKey("LootList") ?? false);
            }
            catch { }
            sb.AppendLine(string.Format("| {0} | `{1}` | {2} | {3} | {4} |",
                b.blockID, b.GetBlockName(), klass, material, isLoot ? "Y" : ""));
        }
        File.WriteAllText(Path.Combine(_outDir, "blocks.md"), sb.ToString());
        return rows.Count;
    }

    // ---- Entities ----

    private int DumpEntities()
    {
        // EntityClass in V2.6 has a static registry, but the field name /
        // container type has shifted across versions (IDictionary, List,
        // typed array). Sweep all static fields on EntityClass and try
        // each collection-typed one — pick the first that yields entities
        // with an entityClassName field.
        const System.Reflection.BindingFlags AllFlags =
            System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic |
            System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Instance;

        var entries = new List<(int id, string name, string tags)>();

        foreach (var f in typeof(EntityClass).GetFields(AllFlags))
        {
            object container = null;
            try
            {
                if (!f.IsStatic) continue;  // need static for the registry
                container = f.GetValue(null);
            }
            catch { continue; }
            if (container == null) continue;

            // Unwrap 7DTD's DictionarySave<K,V> wrapper (and similar): it
            // doesn't implement IDictionary/IEnumerable directly, but exposes
            // the inner Dictionary via a .Dict property or .dic field. Swap
            // the container for the inner dict before type-checking.
            container = UnwrapDictionaryWrapper(container);
            if (container == null) continue;

            // Try as IDictionary (key = class id, value = EntityClass)
            if (container is System.Collections.IDictionary dict && dict.Count > 0)
            {
                TryHarvestFromDict(dict, entries);
                if (entries.Count > 0) break;
            }
            // Try as IEnumerable (List<EntityClass>, typed array, etc.)
            else if (container is System.Collections.IEnumerable en && !(container is string))
            {
                TryHarvestFromEnumerable(en, entries);
                if (entries.Count > 0) break;
            }
        }

        if (entries.Count == 0)
        {
            Log.Warning("[StyxGameRefs] No EntityClass registry located — skipping entities.md. " +
                        "Candidate static fields on EntityClass didn't yield entities with an entityClassName field.");
            return -1;
        }

        entries.Sort((a, b) => string.Compare(a.name, b.name, StringComparison.OrdinalIgnoreCase));

        var sb = new StringBuilder();
        sb.AppendLine("# Entity Classes");
        sb.AppendLine();
        sb.AppendLine("Auto-generated by StyxGameRefs. " + entries.Count + " entity classes registered.");
        sb.AppendLine();
        sb.AppendLine("| ClassId | Name | Tags |");
        sb.AppendLine("|---:|---|---|");
        foreach (var e in entries)
            sb.AppendLine(string.Format("| {0} | `{1}` | {2} |", e.id, e.name, e.tags));

        File.WriteAllText(Path.Combine(_outDir, "entities.md"), sb.ToString());
        return entries.Count;
    }

    /// <summary>
    /// Return the inner Dictionary of a 7DTD DictionarySave-style wrapper, or
    /// the original object if it's already iterable. Looks for common inner-
    /// registry accessors: property `Dict`, field `dic`, property `Inner`,
    /// field `inner`. Returns null only if the input was null.
    /// </summary>
    private static object UnwrapDictionaryWrapper(object container)
    {
        if (container == null) return null;
        // If the container is directly iterable in the shape we want, don't unwrap.
        if (container is System.Collections.IDictionary || container is System.Collections.IEnumerable)
            return container;

        var t = container.GetType();
        var prop = t.GetProperty("Dict") ?? t.GetProperty("Inner");
        if (prop != null)
        {
            try { var inner = prop.GetValue(container); if (inner != null) return inner; } catch { }
        }
        var field = t.GetField("dic") ?? t.GetField("inner");
        if (field != null)
        {
            try { var inner = field.GetValue(container); if (inner != null) return inner; } catch { }
        }
        return container;  // no known wrapper shape — return as-is for sweep to skip
    }

    private static void TryHarvestFromDict(System.Collections.IDictionary dict,
        List<(int id, string name, string tags)> into)
    {
        foreach (System.Collections.DictionaryEntry kv in dict)
            TryAddEntity(kv.Value, kv.Key is int i ? i : 0, into);
    }

    private static void TryHarvestFromEnumerable(System.Collections.IEnumerable en,
        List<(int id, string name, string tags)> into)
    {
        int idx = 0;
        foreach (var o in en)
        {
            TryAddEntity(o, idx++, into);
        }
    }

    private static void TryAddEntity(object ec, int fallbackId,
        List<(int id, string name, string tags)> into)
    {
        if (ec == null) return;
        try
        {
            var t = ec.GetType();

            // Unwrap KeyValuePair<K,V> — DictionarySave<int,EntityClass> (the
            // 7DTD registry type on EntityClass.list) enumerates as KVPs, not
            // as EntityClass directly. Cascade into the Value with Key as id.
            if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(System.Collections.Generic.KeyValuePair<,>))
            {
                var keyProp = t.GetProperty("Key");
                var valProp = t.GetProperty("Value");
                int id = fallbackId;
                if (keyProp != null)
                {
                    var k = keyProp.GetValue(ec);
                    if (k is int kInt) id = kInt;
                }
                var inner = valProp?.GetValue(ec);
                if (inner != null) TryAddEntity(inner, id, into);
                return;
            }

            // Must have entityClassName (field OR property) — sanity check
            // that this is actually an EntityClass and not some other item.
            string name = null;
            var nameField = t.GetField("entityClassName");
            if (nameField != null) name = nameField.GetValue(ec) as string;
            else
            {
                var nameProp = t.GetProperty("entityClassName") ?? t.GetProperty("Name");
                if (nameProp != null) name = nameProp.GetValue(ec) as string;
            }
            if (string.IsNullOrEmpty(name)) return;

            // Pull an id field if present; otherwise use the passed fallback.
            int resolvedId = fallbackId;
            var idField = t.GetField("entityClassId") ?? t.GetField("classId") ?? t.GetField("id");
            if (idField != null)
            {
                var idVal = idField.GetValue(ec);
                if (idVal is int intId) resolvedId = intId;
            }

            string tags = "";
            try
            {
                var tagsField = t.GetField("Tags") ?? t.GetField("tags");
                var tagsObj = tagsField?.GetValue(ec);
                tags = tagsObj?.ToString() ?? "";
            }
            catch { }
            into.Add((resolvedId, name, tags));
        }
        catch { }
    }

    // ---- Buffs ----

    private int DumpBuffs()
    {
        // V2.6 doesn't expose BuffManager.Instance the way earlier versions
        // did. The buff registry lives somewhere accessible but the field
        // name varies, so search defensively across the known candidate
        // holders: BuffManager (static + instance), BuffClass (static).
        System.Collections.IDictionary dict = null;
        const System.Reflection.BindingFlags AllFlags =
            System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic |
            System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Instance;

        // Try static dicts on the classes themselves (V2.6 pattern).
        foreach (var t in new[] { typeof(BuffManager), typeof(BuffClass) })
        {
            foreach (var f in t.GetFields(AllFlags))
            {
                if (!typeof(System.Collections.IDictionary).IsAssignableFrom(f.FieldType)) continue;
                object container = null;
                if (!f.IsStatic)
                {
                    // Instance field — need an instance. Look for a static Instance prop/field
                    // on the same type.
                    var instProp = t.GetProperty("Instance", AllFlags);
                    var instField = t.GetField("Instance", AllFlags);
                    try { container = instProp?.GetValue(null) ?? instField?.GetValue(null); } catch { }
                    if (container == null) continue;
                }
                object candidate;
                try { candidate = f.GetValue(container); } catch { continue; }
                if (candidate is System.Collections.IDictionary d && d.Count > 0) { dict = d; break; }
            }
            if (dict != null) break;
        }

        if (dict == null)
        {
            Log.Warning("[StyxGameRefs] Buff registry dict not located on BuffManager or BuffClass — skipping buffs.md");
            return -1;
        }

        var entries = new List<(string name, bool hidden, string nameKey)>();
        foreach (System.Collections.DictionaryEntry kv in dict)
        {
            try
            {
                string name = kv.Key as string ?? kv.Value?.GetType().GetField("Name")?.GetValue(kv.Value)?.ToString() ?? "";
                if (string.IsNullOrEmpty(name)) continue;
                bool hidden = false;
                string nameKey = "";
                try
                {
                    var bc = kv.Value;
                    var hiddenField = bc.GetType().GetField("Hidden") ?? bc.GetType().GetField("hidden");
                    if (hiddenField != null) hidden = (bool)hiddenField.GetValue(bc);
                    var nkField = bc.GetType().GetField("NameKey") ?? bc.GetType().GetField("nameKey");
                    if (nkField != null) nameKey = (string)(nkField.GetValue(bc) ?? "");
                }
                catch { }
                entries.Add((name, hidden, nameKey));
            }
            catch { }
        }
        entries.Sort((a, b) => string.Compare(a.name, b.name, StringComparison.OrdinalIgnoreCase));

        var sb = new StringBuilder();
        sb.AppendLine("# Buffs");
        sb.AppendLine();
        sb.AppendLine("Auto-generated by StyxGameRefs. " + entries.Count + " buffs registered.");
        sb.AppendLine();
        sb.AppendLine("| Name | NameKey | Hidden |");
        sb.AppendLine("|---|---|:---:|");
        foreach (var b in entries)
            sb.AppendLine(string.Format("| `{0}` | {1} | {2} |", b.name, b.nameKey, b.hidden ? "Y" : ""));

        File.WriteAllText(Path.Combine(_outDir, "buffs.md"), sb.ToString());
        return entries.Count;
    }
}
